version: '3.8'

services:
  discord-music-bot:
    build: .
    container_name: music_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
     - ./sounds:/app/sounds  
     - ./music:/app/music 

    